// <auto-generated />
namespace Samy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11072017AlumnosExamen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11072017AlumnosExamen));
        
        string IMigrationMetadata.Id
        {
            get { return "201707120429002_11072017AlumnosExamen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
